#
# This file provides the mapping between ROS joint names in JointState (and
# other messages that use joint names) and the indices which should be used
# for those joints in the DynamicJointPoint and DynamicJointState messages.
#
# Note that although supported, no namespaces are configured. In that case
# JointState, FollowJointTrajectoryFeedback, RobotStatus and the
# 'joint_path_command' topics will all be pushed down into those namespaces.
#
# Note also that the value set in the 'group' key should correspond to whatever
# identification the controller uses to identify the motion group. It is *not*
# an index into the 'controller_joint_map' (so it does not need to be
# sequential: for a controller with 2 motion groups, identified as 'group 1'
# and 'group 3', the 'group' keys would be 1 and 3 respectively, *not* 1 and 2).
#
controller_joint_map:
    # these joints are mapped into motion group 1 on the controller
  - group: 1
    ns: ""
    joints: [left_joint_1, left_joint_2, left_joint_3, left_joint_4, left_joint_5, left_joint_6]
    # these joints are mapped into motion group 2 on the controller
  - group: 2
    ns: ""
    joints: [right_joint_1, right_joint_2, right_joint_3, right_joint_4, right_joint_5, right_joint_6]
